### ISSUE TITLE
Pushing fresh repo fails due to unknown Git LFS objects

### ISSUE THREAD

**Issue by daredyoshi** [sinbad/lfs-folderstore#13]
Hey there,
Thanks for writing this nifty tool. I tried setting things up for my game as you described in the readme, but am getting the following error when executing ```git push origin master```

```
git push origin master                                                                                                                  ─╯
Uploading LFS objects: 100% (1033/1033), 2.4 GB | 205 MB/s, done.
Enumerating objects: 5327, done.
Counting objects: 100% (5327/5327), done.
Delta compression using up to 16 threads
Compressing objects: 100% (5324/5324), done.
Writing objects: 100% (5327/5327), 17.38 MiB | 8.17 MiB/s, done.
Total 5327 (delta 2668), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2668/2668), done.
remote: error: GH008: Your push referenced at least 40 unknown Git LFS objects:
remote:     d2d36233d085db6ebd5aa073a3fff219f1c67e0e7a2243da1b2f761cdc404290
remote:     8ba285d22695b67ff5fcde886abf789d06680ee564f9f079d5d2e7cbab35931c
remote:     80ee32ab0756c44afc3cb8e2e0f138c9f78dc687387e5bc653c2c6cc3f033510
remote:     ...
remote: Try to push them with 'git lfs push --all'.
To https://github.com/myGameUrl.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

Any ideas why this could be happening? I did try to push them with ```git lfs push --all```, but it makes no difference.

All the files are in my lfs-folder as expected.

**Comment by daredyoshi** [comment]
After some more testing I realized even though I hadn't pushed any successfull commits due to my git account capacity, github must have nonetheless stored references to my lfs object and was refusing things because of that. I deleted and re-created my repo and things worked!

**Comment by sinbad** [comment]
Yep ironically if you want to use GitHub for commit storage but not for LFS storage you have to turn *off* the LFS option on your GitHub repo so it doesn't look for the objects you're referencing.
