### ISSUE TITLE
Question About Setting This Up

### ISSUE THREAD

**Issue by WeirdBeardDev** [sinbad/lfs-folderstore#2]
I'm relatively new to git, been using it for the last few months, and I'm completely new to LFS.  I'm working on learning game dev with Unity and had LFS configured for github but quickly exceeded the storage limit.  I am trying to accomplish having my code repo point to github while the lfs repo is on a local folder where Dropbox will backup the large files.  Your solution seems to fit my needs perfectly, but I can't get it to work.

Here are some relevant details:
Windows 10
git v2.21.0.windows.1
lfs v2.7.1
code base (lfs pointers) - github.com
lfs files - d:dropbox\dev\lfs\sandbox

I can't get the `git remote add folderremote <url>` command to take.  I read that remotes can use `file://` and tried `file:////d:/dropbox/dev/lfs/sandbox`, however, `git lfs env` displays it as `Endpoint=https://d////Dropbox/Dev/LFS/Sandbox (auth=none)` followed by `SSH=d:///Dropbox/Dev/LFS/Sandbox`.  Then when I push I get an error saying `ssh: Could not resolve hostname d: ...`.

When I take the `file://` out then LFS config usually reports `Endpoint=<unknown> (auth=none)` and `Endpoint (folderremote)=<unknown> (auth=none)`.

This leads to another point of confusion for me, the `lfs.<url>.standalonetransferagent` command.  I assume for a file location it would look something like `lfs.d:/dropbox/dev/lfs/sandbox.standalonetransferagent=lfs-folder`.

What am I missing?

While typing this I thought about trying to use the Dropbox URL for my remote URL.  I'll test that next.

**Comment by ZeusLT** [comment]
<url> has to be link to your github repo for example https://github.com/ZeusLT/example-project.git

**Comment by WeirdBeardDev** [comment]
Everything ran without errors, however, after the `git push ...` shouldn't I see something in the Dropbox folder?  I put my [git config and lfs env ](https://pastebin.com/cU2DJjin)on pastebin.

**Comment by ZeusLT** [comment]
lfs-folderstore.exe has to be in one of the folders of system environment variables "PATH". For example in system32.

**Comment by WeirdBeardDev** [comment]
I got it, I'm not sure what I was doing wrong before but I tried it on a fresh repo and it worked.

Thanks for your help.
