### ISSUE TITLE
Spaces in NAS folder path

### ISSUE THREAD

**Issue by jinincarnate** [sinbad/lfs-folderstore#4]
!!Need help!!
git config --add lfs.customtransfer.lfs-folder.args "C:/path/to/your/folder"

'git push origin master' breaks if the path has spaces in between example "C:/path with space/to/your/folder"

**Comment by jinincarnate** [comment]
Few!! figured it
By adding single quotes to the path in local git config file.

[lfs "customtransfer.lfs-folder"]
	path = lfs-folderstore
	args = 'C:/path with space/to/your/folder' <-------------------------like this

Thanks for such an awesome Project though :)

**Comment by penut85420** [comment]
@jinincarnate thanks! This helped me with my google drive.
Thanks to this awesome project too, hope this issue can be mention in README! @sinbad

**Comment by sinbad** [comment]
I've added a note to the Readme, sorry I didn't think to do that earlier.
