### ISSUE TITLE
error: failed to push some refs to 'https://github.com/...'

### ISSUE THREAD

**Issue by sbrt** [sinbad/lfs-folderstore#6]
Hi!

I tried using lfs-folderstore using the Readme instructions, but I get an error.

I used a simple test repo with a single file.

git version 2.25.1
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
lfs-folderstore build with 'go build'

> git init
> git lfs install
> git add .
> git commit -m "."
> git config --add lfs.customtransfer.lfs-folder.args PATH
> git config --add lfs.customtransfer.lfs-folder.path lfs-folderstore
> git config --add lfs.standalonetransferagent lfs-folder
> git push --set-upstream origin master
>EOFoading LFS objects: 100% (1/1), 43 MB | 0 B/s                                             
>error: failed to push some refs to 'https://github.com/sbrt/test.git'

Using github LFS works fine.

Any guess what might be causing this, other than version incompatibilities?

**Comment by mstanki-ra** [comment]
I had same issue.
I have used as remote a company-internal GitLab instance with Git LFS enabled, so I thought this may be the reason.

I was suggested to follow the [_Configure an existing repo_](https://github.com/sinbad/lfs-folderstore#configure-an-existing-repo) section, which explicitly says "If you already have a Git LFS repository **pushing to a standard LFS server**"

I have used the repository created earlier (going through _Configure a fresh repo_ section), which already had one LFS file (stored in my GitLab's LFS).
I have cloned the repo and followed the steps starting from `git remote add folderremote <url>` with `<url>` set to the repo I have cloned from,

```
git remote add folderremote https://<my-gitlab>/git-lfs-folderstore-playground.git
git config --add lfs.customtransfer.lfs-folder.path lfs-folderstore
git config --add lfs.customtransfer.lfs-folder.args "C:\Users\<my-directory>\git-lfs-folderstore-playground"
git config --add lfs.https://<my-gitlab>/git-lfs-folderstore-playground.git.standalonetransferagent lfs-folder
```

I have added new LFS-tracked file as `git push folderremote master` told me "Everything up-to-date".

After commiting new LFS-tracked file I tried again:
```
$ git push -v folderremote master
Pushing to https://<my-gitlab>/git-lfs-folderstore-playground.git
Uploading LFS objects: 100% (2/2), 1.0 MB | 0 B/s, done.
EOF
error: failed to push some refs to 'https://<my-gitlab>/git-lfs-folderstore-playground.git'
```
The error message says _Uploading LFS objects: 100%_, but the large files did not appear in my local storage `C:\Users\<my-directory>\git-lfs-folderstore-playground`.

**Comment by sinbad** [comment]
Sorry for the late reply, I unwittingly had notifications disabled on this repo. 

lfs-folderstore was not designed for use with servers which have their own LFS implementations. Their response codes may well override the transfer agent (it's been too long since I worked on the git-lfs core so I can't quite remember the specifics, and they may have changed).

You can obtain more information by setting `GIT_TRACE=1` in the terminal before calling your command.

**Comment by k-nkmt** [comment]
I had same issue.
Set `GIT_TRACE=1` and I got this message.
```
trace git-lfs: xfer[lfs-folderstore]: sh: lfs-folderstore: command not found
EOFoading LFS objects: 100% (1/1), x.x KB | 0 B/s
error: failed to push some refs to 'xxx'
```
I added to PATH on windows 10, but it was not reflected to git bash.
After setting the PATH for bash, it worked as expected.
